### ISSUE TITLE
Copyright Notice in License is missing 

### ISSUE THREAD

**Issue by divyank-vwits** [spring-projects/spring-data-dev-tools#186]
For companies that use this library, it is important to understand who is the copyright holder.
In the license file that is attached, the copyright holder is not clearly stated but it is still kept as the template value.

It would be great if you could add the name(s) of the copyright holder such that the legal situation gets clarified properly.

**Comment by mp911de** [comment]
I think there's a general misunderstanding. This project contains utilities to ship a Spring Data release. It isn't intended to be used by anyone else other than the Spring Data maintainers. 

Is there a use case in which you would want to use functionality from this project?

**Comment by mp911de** [comment]
The same argument as the similar issue on Spring Boot applies. spring-projects/spring-boot#27021
