### ISSUE TITLE
Make detection of Java home work with JDKs > 8

### ISSUE THREAD

**Issue by schauder** [spring-projects/spring-data-dev-tools#196]
This https://github.com/spring-projects/spring-data-dev-tools/blob/5b80d492f570b6d87f328a78b8b716e214e32be5/release-tools/src/main/java/org/springframework/data/release/io/CommonsExecOsCommandOperations.java#L159
seems to only work for JDK 1.8

**Comment by mp911de** [comment]
Yeah, as we require Java 1.8.
