### ISSUE TITLE
Add support to create release tickets

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-data-dev-tools#5]

**Comment by mp911de** [comment]
Requires:
* Create Jira project version/Github milestone if not exists
* Create release ticket if not exists
* List release tickets

Specialties:
* Projects have either an `Infrastructure` component in Jira or not, needs to be configured somewhere (`Project`?)

**Comment by olivergierke** [comment]
Can we just set the latter if it exists for the project and just skip it if not?

**Comment by mp911de** [comment]
Sure, requires an additional lookup.
